pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        sh 'cat /etc/os-* >> /home/ubuntu/system.txt'
      }
    }
  }
}
